import { Permission } from '../enums/permission.enum';
import { Role } from '../enums/role.enum';

export const RolePermissions: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: Object.values(Permission),
  [Role.ADMIN]: [
    Permission.PROFILE_READ,
    Permission.USERS_READ,
    Permission.USERS_CREATE,
    Permission.USERS_UPDATE,
    Permission.PRODUCTS_READ,
    Permission.PRODUCTS_CREATE,
    Permission.PRODUCTS_UPDATE,
    Permission.PRODUCTS_DELETE,
    Permission.SERVICES_READ,
    Permission.SERVICES_CREATE,
    Permission.SERVICES_UPDATE,
    Permission.SERVICES_DELETE,
    Permission.QUOTATIONS_READ,
    Permission.QUOTATIONS_CREATE,
    Permission.QUOTATIONS_UPDATE,
    Permission.CLIENTS_READ,
    Permission.CLIENTS_CREATE,
    Permission.CLIENTS_UPDATE,
    Permission.CLIENTS_DELETE,
    Permission.SALES_READ,
    Permission.SALES_CREATE,
    Permission.SALES_UPDATE,
    Permission.SUPPLIERS_READ,
    Permission.SUPPLIERS_CREATE,
    Permission.SUPPLIERS_UPDATE,
    Permission.SUPPLIERS_DELETE,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_CREATE,
    Permission.PURCHASE_ORDERS_READ,
    Permission.PURCHASE_ORDERS_CREATE,
    Permission.PURCHASE_ORDERS_UPDATE,
    Permission.PURCHASES_READ,
    Permission.PURCHASES_CREATE,
    Permission.INVOICES_READ,
    Permission.INVOICES_CREATE,
    Permission.REPORTS_READ,
  ],
  [Role.USER]: [
    Permission.PROFILE_READ,
    Permission.PRODUCTS_READ,
    Permission.SERVICES_READ,
    Permission.QUOTATIONS_READ,
    Permission.QUOTATIONS_CREATE,
    Permission.QUOTATIONS_UPDATE,
    Permission.CLIENTS_READ,
    Permission.CLIENTS_CREATE,
    Permission.CLIENTS_UPDATE,
    Permission.SALES_READ,
    Permission.SALES_CREATE,
    Permission.SALES_UPDATE,
    Permission.SUPPLIERS_READ,
    Permission.INVENTORY_READ,
    Permission.PURCHASE_ORDERS_READ,
    Permission.PURCHASES_READ,
    Permission.INVOICES_READ,
    Permission.REPORTS_READ,
  ],
};
